// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMuJx3sk8FTl_qKxl4MfhEsQdcufm_1-0',
    appId: '1:79610139654:web:09a0b05d54d311823a1f87',
    messagingSenderId: '79610139654',
    projectId: 'timewise-1dabc',
    authDomain: 'timewise-1dabc.firebaseapp.com',
    storageBucket: 'timewise-1dabc.firebasestorage.app',
    measurementId: 'G-TBE29HWXS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjXfemWP60yZKf1zOarqta8dPHQ_wSGao',
    appId: '1:79610139654:android:d322cbdad63ea1ae3a1f87',
    messagingSenderId: '79610139654',
    projectId: 'timewise-1dabc',
    storageBucket: 'timewise-1dabc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAad5fLpYfesitcAu8ESoBGBoOvHrslxnI',
    appId: '1:79610139654:ios:1a2f1fe8fb3799773a1f87',
    messagingSenderId: '79610139654',
    projectId: 'timewise-1dabc',
    storageBucket: 'timewise-1dabc.firebasestorage.app',
    iosClientId: '79610139654-4irlj6un07fisot52j5kpr2db85chb1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.timewise',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAad5fLpYfesitcAu8ESoBGBoOvHrslxnI',
    appId: '1:79610139654:ios:1a2f1fe8fb3799773a1f87',
    messagingSenderId: '79610139654',
    projectId: 'timewise-1dabc',
    storageBucket: 'timewise-1dabc.firebasestorage.app',
    iosClientId: '79610139654-4irlj6un07fisot52j5kpr2db85chb1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.timewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMuJx3sk8FTl_qKxl4MfhEsQdcufm_1-0',
    appId: '1:79610139654:web:c985ef0525df86933a1f87',
    messagingSenderId: '79610139654',
    projectId: 'timewise-1dabc',
    authDomain: 'timewise-1dabc.firebaseapp.com',
    storageBucket: 'timewise-1dabc.firebasestorage.app',
    measurementId: 'G-0T0SMGQWPC',
  );
}
